### ISSUE TITLE
Create admin app for App.co

### ISSUE THREAD

**Issue by jeffdomke** [blockstack/app.co#420] opened 2019-01-08 20:27 UTC
This project that entails the creation of a separate administration app for App.co powered by Blockstack.

**Comment by friedger** [comment] 2019-05-23 18:46
I started something at gitlab.com/friedger/appcostats

appcostats.openintents.org

It is our data!

**Comment by hstove** [comment] 2019-11-11 23:02
Closing this, as it's basically another duplicate of Maker Portal work.

**Closed by hstove** 2019-11-11 23:02 UTC
Labels: Epic
