### ISSUE TITLE
Ensure that email address in addition to timestamp entered into spreadsheet upon start kit form submission

### ISSUE THREAD

**Issue by GinaAbrams** [blockstack/app.co#423] opened 2019-01-10 16:54 UTC
@hstove following up from stand-up to investigate the blank fields with timestamps 🙏

**Comment by hstove** [comment] 2019-01-15 17:39
I just fixed this. I'm assigning to @GinaAbrams to confirm.

**Comment by markmhx** [comment] 2019-01-28 14:43
@GinaAbrams Have you been able to confirm that this works as intended? If so, let's close the issue out.

**Closed** 2019-01-28 14:51 UTC
Labels: bug
