### ISSUE TITLE
Quality check on TryMyUI

### ISSUE THREAD

**Issue by jeffdomke** [blockstack/app.co#478] opened 2019-03-22 14:56 UTC
I've heard a few reports of the testers not getting into the app. If my memory is correct, TryMyUI should have instructions that the test must login. Also they have some review procedures in place to retest bad sessions. If that is not happening, we need to identify the problem clearly and ask TryMyUI to fix the issue.

**Comment by markmhx** [comment] 2019-03-25 17:39
@GinaAbrams is going to check into the auditing process currently run by TryMyUI and I'll be reviewing the latest batch of videos to see how many testers do or don't get into apps.

**Comment by markmhx** [comment] 2019-04-09 14:17
I'm closing this since I believe we've confirmed that quality is fine generally, and remaining issues with getting into apps more concern the need for blockstack.js upgrades than anything else.

**Closed by markmhx** 2019-04-09 14:17 UTC
